use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MAGUMVerify_Example' do
  pod 'MAGUMVerify', :path => '../'

  target 'MAGUMVerify_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
